### ISSUE TITLE
:bug: onClick Link the wrong link data is sent

### ISSUE THREAD

**Issue by guillaumecrespel** [unirakun/react-kgraph#32]
**branch:** master

![image](https://user-images.githubusercontent.com/26094222/76837325-abe84180-6832-11ea-973f-59acfa1ddaf1.png)

**Comment by fabienjuif** [comment]
Which branch?

**Comment by fabienjuif** [comment]
@guillaumecrespel which branch? do you reproduce this on the master?

**Comment by guillaumecrespel** [comment]
this screenshot is on #30 but I reproduce on master too.

**Comment by fabienjuif** [comment]
Ok, I'll look at it tomorrow

**Comment by fabienjuif** [comment]
I think this is because makeCurvedLinks does not preserve links order
