### ISSUE TITLE
:recycle: extract propTypes on types folder.

### ISSUE THREAD

**Issue by guillaumecrespel** [unirakun/react-kgraph#33]
![image](https://user-images.githubusercontent.com/26094222/76837918-a0e1e100-6833-11ea-8d54-b4beea20684f.png)

This lint error is resolve by extract propTypes of link in other ts  file.
And why not extract all PropTypes on types folder ?

**Comment by fabienjuif** [comment]
You can extract this one on the types folder in your PR.
Why this one and not the others?

Because types folder is meant to be exposed as an API, the LinkProps is part of the API so I am ok to expose it, others are not right now, so we can let them in files with code.
